### ISSUE TITLE
Broken npm package

### ISSUE THREAD

**Issue by cleaton** [Code-Hex/firebase-auth-cloudflare-workers#5]
Hi, I got the following error trying to use the npm published package https://www.npmjs.com/package/firebase-auth-cloudflare-workers
'The package may have incorrect main/module/exports specified in its package.json'
this is because package.json sets `"module": "dist/module/index.mjs",` but the actual file is 'dist/module/index.**js**'

**Comment by Code-Hex** [comment]
@cleaton Thanks for reporting!
I'm not sure what your enviroment. (i.e. JavaScript or TypeScript)

I can use this package in https://github.com/honojs/firebase-auth/blob/63f5e0c5c1989de632fca1e1e96265094a624d0e/package.json#L31

**Comment by cleaton** [comment]
I use typescript bundled to ES module (not common js) , it’s part of a SSR project using  vite (esbuild) for bundling. For now I’ve manually updated the “module” path and it works

Looks like the firebase-auth library uses commonjs with esmodule interoperability instead of pure esmodule

**Comment by qqap** [comment]
Hi! @cleaton how did you update the “module” path to make it work. Was it in the Vite config? Ty!

This is what I see is in the package.json for this package.
```
  "main": "dist/main/index.js",
  "typings": "dist/main/index.d.ts",
  "module": "dist/module/index.mjs",
```

**Comment by Code-Hex** [comment]
Probably, now resolved this issue

**Comment by lamplightdev** [comment]
I also get this error, and maybe I'm not understanding, but the `dist/module` folder in the package contents has `index.js`, so I think it should be `"module": "dist/module/index.js"`

<img width="812" alt="Screenshot 2024-01-18 at 23 50 09" src="https://github.com/Code-Hex/firebase-auth-cloudflare-workers/assets/898995/13dd30c9-bc94-448c-bb1d-fa462f0054ad">
