### ISSUE TITLE
Question about configuration

### ISSUE THREAD

**Issue by timmushen** [Code-Hex/firebase-auth-cloudflare-workers#6]
Hi, I have a question relating to configuration. 

I'm able to authenticate with an express firebase-admin script. When I try on Cloudflare I receive the following error: 

"err": {
    "code": "auth/argument-error",
    "message": "Error fetching public keys for Google certs: TypeError: Cannot read properties of undefined (reading 'get')"
  }

Thank you for making this! I'm very excited to use it.

**Comment by Code-Hex** [comment]
@timmushen Hi! Thanks for asking your question!

But, I cannot understand why this is happened the error from only you provided information. Could you share me your wrangler.toml?

By the way, I appreciate you with sponsoring me! Thank you so much!

**Comment by timmushen** [comment]
@Code-Hex My pleasure! Thank you for your contributions to the community. 

Here's my wrangler.toml. I believe it's an issue with the PUBLIC_JWT_CACHE_KEY... I'm not exactly sure what should go here. 

name="hono-minimal"
main="src/index.ts"
compatibility_date = "2022-10-12"
[vars]
PUBLIC_JWK_CACHE_KEY = "https://www.googleapis.com/robot/v1/metadata/x509/*omitted service account email*"
PROJECT_ID = "salonspasites"
kv_namespaces =[{ binding = "salonspaauth", id = "a88b99020b8b44caa75155ba38ee6b66" }]

**Comment by Code-Hex** [comment]
@timmushen I'm sorry for the delay.
Yes, This `PUBLIC_JWK_CACHE_KEY` means the name of the cache (use Cloudflare KV by default) key.

This package has the ability to automatically retrieve the jwk hosted by Google, and save the jwk file to the cache. This key name is used for that.

This is example for wrangler.toml.
https://github.com/Code-Hex/firebase-auth-cloudflare-workers/blob/a2d752f3320291c710afe0ebb5f3d67d79c10ff0/example/wrangler.toml#L26-L27

**Comment by timmushen** [comment]
That did it! Thank you so much for your help.
